export const metadata = {
  title: {
    default: "Next js Practice",
    template: "%s | Next js",
  },
  description: "Generated by Next.js",
};

import Link from "next/link";
import "./globals.css";
import Nav from "../components/Nav";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-[#151515] text-white font-gilroy  w-[100%] h-[100vh]">
        <header>
          <Nav />
        </header>
        {children}
        {/* <footer>
          <p>Copyright © 2022 Next.js</p>
        </footer> */}
      </body>
    </html>
  );
}
